services:
  app:
    container_name: sobaki
    env_file:
      - .env
    ports:
      - "8091:8091"
    networks:
      - backend
      
    volumes:
      - shared-data:/app/shared
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
    build:
      context: .
      dockerfile: Dockerfile

  worker:
    container_name: worker-sobaki

    ports:
      - "8001:8001"
    networks:
      - backend
    volumes:
      - shared-data:/app/shared

    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
    build:
      context: pkg/zalupa
      dockerfile: Dockerfile

volumes:
  shared-data:

networks:
  backend:
    driver: bridge