DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS external_users CASCADE;
DROP TABLE IF EXISTS applicants CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ter_otdels CASCADE;
DROP TABLE IF EXISTS districts CASCADE;
DROP TABLE IF EXISTS roles CASCADE;