// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Смена данных профлия пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Change Profile Info",
                "parameters": [
                    {
                        "description": "Change Profile information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangeProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация успешна изменена.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "500": {
                        "description": "Ошибка при cмене  данных.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновление токенов доступа и обновления.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthTokens"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthTokens"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthTokens"
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "description": "Авторизация пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign In",
                "parameters": [
                    {
                        "description": "Account credentials",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthCredentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "Регистрация нового пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign Up",
                "parameters": [
                    {
                        "description": "Account information",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Account"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    }
                }
            }
        },
        "/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение всех запросов на отлов бродячих собак. Доступно только для районных администраторов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get All Requests",
                "responses": {
                    "200": {
                        "description": "Все заявки",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.RequestFull"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении запросов.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отправка запроса на отлов бродячей собаки. Поля source_id и applicant_id заполнять ID из справочников. Поля name в этих полях игнорируются при отправке запроса. Доступно для всех авторизованных пользователей.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Send Request",
                "parameters": [
                    {
                        "description": "Request information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestFull"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос успешно отправлен",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "500": {
                        "description": "Ошибка при отправке запроса",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/requests/change-status": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменение статуса заявки на отлов бродячей собаки. Поля id и status обязательны к заполнению.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Change Status Request",
                "parameters": [
                    {
                        "description": "Change Status Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangeStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статус заявки успешно изменен.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "500": {
                        "description": "Ошибка при изменении статуса заявки.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/requests/download_url": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение URL для скачивания файла заявки в формате .docx. Требуется параметр number в query, номер заявки. Доступно для всех авторизованных пользователей.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Download Request File URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request Number",
                        "name": "number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseUrl"
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении запросов.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/requests_otdel": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение запросов на отлов бродячих собак по отделу. Требуется параметр otdel_id в query, otdel_id находится в справочнике. Доступно только для районных администраторов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get Requests By Otdel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Otdel ID",
                        "name": "otdel_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.RequestFull"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка в данных запроса.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении запросов.",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение профиля пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Account": {
            "description": "Структура для создания учетной записи пользователя. Все поля обязательны к заполнению",
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя или название организации",
                    "type": "string"
                },
                "id": {
                    "description": "ID пользователя",
                    "type": "string"
                },
                "login": {
                    "description": "Логин для входа в систему, должен быть уникальным",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль для входа в систему",
                    "type": "string"
                },
                "role": {
                    "description": "Роль пользователя, например, \"admin\", \"user\", \"otdel\" и т.д.",
                    "type": "string"
                }
            }
        },
        "dto.Applicant": {
            "description": "Заявитель. Поле name игнорируется при создании заявки.",
            "type": "object",
            "properties": {
                "id": {
                    "description": "уникальный идентификатор заявителя при Post запросе на создание заявки ОБЯЗАТЕЛЕН",
                    "type": "string"
                },
                "name": {
                    "description": "Название заявителя игнорируется при создании заявки",
                    "type": "string"
                }
            }
        },
        "dto.AuthCredentials": {
            "description": "Структура для авторизации пользователя. Все поля обязательны к заполнению",
            "type": "object",
            "properties": {
                "login": {
                    "description": "Логин для входа в систему, должен быть уникальным",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль для входа в систему",
                    "type": "string"
                }
            }
        },
        "dto.AuthResponse": {
            "description": "Структура для ответа с данными пользователя",
            "type": "object",
            "properties": {
                "message": {
                    "description": "просто сообщение",
                    "type": "string"
                },
                "status": {
                    "description": "обычно ok  при ошибках error",
                    "type": "string"
                },
                "tokens": {
                    "description": "токены авторизации",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.AuthTokens"
                        }
                    ]
                },
                "user": {
                    "description": "данные пользователя",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserProfile"
                        }
                    ]
                }
            }
        },
        "dto.AuthTokens": {
            "description": "Структура c токенами",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refhresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.ChangePasswordRequest": {
            "description": "Структура для смены пароля пользователя. Все поля обязательны к заполнению",
            "type": "object",
            "properties": {
                "login": {
                    "description": "Логин для входа в систему, должен быть уникальным",
                    "type": "string"
                },
                "new_password": {
                    "description": "Новый пароль для входа в систему",
                    "type": "string"
                },
                "old_password": {
                    "description": "Старый пароль для входа в систему",
                    "type": "string"
                }
            }
        },
        "dto.ChangeProfileRequest": {
            "description": "Структура для отправки запроса на изменение данных профиля",
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя или название организации",
                    "type": "string"
                },
                "id": {
                    "description": "ID пользователя",
                    "type": "string"
                },
                "login": {
                    "description": "Логин для входа в систему, должен быть уникальным",
                    "type": "string"
                }
            }
        },
        "dto.ChangeStatusRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID заявки",
                    "type": "string"
                },
                "status": {
                    "description": "Новый статус заявки (новая, в работе, выполнена, отменена)",
                    "type": "string"
                }
            }
        },
        "dto.RequestFull": {
            "description": "Полная информация о заявке на отлов бродячей собаки. Поля id, number, status и created_at игнорируются при создании заявки.",
            "type": "object",
            "properties": {
                "address": {
                    "description": "Адрес, где была замечена бродячая собака",
                    "type": "string"
                },
                "applicant": {
                    "description": "Заявитель ID находится в справочнике",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Applicant"
                        }
                    ]
                },
                "behavior": {
                    "description": "Поведение собаки",
                    "type": "string"
                },
                "contact_person": {
                    "description": "Контактные данные",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата и время создания заявки генерируется автоматически",
                    "type": "string"
                },
                "dogs_count": {
                    "description": "Количество собак",
                    "type": "integer"
                },
                "id": {
                    "description": "уникальный идентификатор заявки при Post запросе не указывается",
                    "type": "string"
                },
                "number": {
                    "description": "уникальный номер заявки, генерируется автоматически при создании заявки",
                    "type": "string"
                },
                "source": {
                    "description": "Источник информации от кого был получен запрос ID находится в справочнике",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Source"
                        }
                    ]
                },
                "status": {
                    "description": "Статус заявки (новая, в работе, выполнена, отменена) генерируется после создания заявки",
                    "type": "string"
                },
                "urgency": {
                    "description": "срочность",
                    "type": "string"
                }
            }
        },
        "dto.Response": {
            "description": "Структура для ответа с где обычно ок и сообщние",
            "type": "object",
            "properties": {
                "message": {
                    "description": "просто сообщение",
                    "type": "string"
                },
                "status": {
                    "description": "обычно ok  при ошибках error",
                    "type": "string"
                }
            }
        },
        "dto.ResponseUrl": {
            "description": "Структура для ответа с где обычно ок и url",
            "type": "object",
            "properties": {
                "status": {
                    "description": "обычно ok  при ошибках error",
                    "type": "string"
                },
                "url": {
                    "description": "url на скаччивание файла",
                    "type": "string"
                }
            }
        },
        "dto.Source": {
            "description": "Источник информации от кого был получен запрос. Поле name игнорируется при создании заявки.",
            "type": "object",
            "properties": {
                "id": {
                    "description": "уникальный идентификатор источника при Post запросе на создание заявки ОБЯЗАТЕЛЕН",
                    "type": "string"
                },
                "name": {
                    "description": "Название источника игнорируется при создании заявки",
                    "type": "string"
                }
            }
        },
        "dto.UserProfile": {
            "description": "Структура для получения профиля пользователя. Все поля обязательны к заполнению",
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя или название организации",
                    "type": "string"
                },
                "id": {
                    "description": "ID пользователя",
                    "type": "string"
                },
                "login": {
                    "description": "Логин для входа в систему, должен быть уникальным",
                    "type": "string"
                },
                "role": {
                    "description": "Роль пользователя, например, \"admin\", \"user\", \"otdel\" и т.д.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8091",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Go Dog Trapping API",
	Description:      "API сервиса для отлова бродячих собак.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
