basePath: /api
definitions:
  dto.Account:
    description: Структура для создания учетной записи пользователя. Все поля обязательны
      к заполнению
    properties:
      full_name:
        description: Полное имя или название организации
        type: string
      login:
        description: Логин для входа в систему, должен быть уникальным
        type: string
      password:
        description: Пароль для входа в систему
        type: string
      role:
        description: Роль пользователя, например, "admin", "user", "otdel" и т.д.
        type: string
    type: object
  dto.Applicant:
    description: Заявитель. Поле name игнорируется при создании заявки.
    properties:
      id:
        description: уникальный идентификатор заявителя при Post запросе на создание
          заявки ОБЯЗАТЕЛЕН
        type: string
      name:
        description: Название заявителя игнорируется при создании заявки
        type: string
    type: object
  dto.AuthCredentials:
    description: Структура для авторизации пользователя. Все поля обязательны к заполнению
    properties:
      login:
        description: Логин для входа в систему, должен быть уникальным
        type: string
      password:
        description: Пароль для входа в систему
        type: string
    type: object
  dto.ChangePasswordRequest:
    description: Структура для смены пароля пользователя. Все поля обязательны к заполнению
    properties:
      login:
        description: Логин для входа в систему, должен быть уникальным
        type: string
      new_password:
        description: Новый пароль для входа в систему
        type: string
      old_password:
        description: Старый пароль для входа в систему
        type: string
    type: object
  dto.RequestFull:
    description: Полная информация о заявке на отлов бродячей собаки. Поля id, number,
      status и created_at игнорируются при создании заявки.
    properties:
      address:
        description: Адрес, где была замечена бродячая собака
        type: string
      applicant:
        allOf:
        - $ref: '#/definitions/dto.Applicant'
        description: Заявитель ID находится в справочнике
      behavior:
        description: Поведение собаки
        type: string
      contact_person:
        description: Контактные данные
        type: string
      created_at:
        description: Дата и время создания заявки генерируется автоматически
        type: string
      dogs_count:
        description: Количество собак
        type: integer
      id:
        description: уникальный идентификатор заявки при Post запросе не указывается
        type: string
      number:
        description: уникальный номер заявки, генерируется автоматически при создании
          заявки
        type: string
      source:
        allOf:
        - $ref: '#/definitions/dto.Source'
        description: Источник информации от кого был получен запрос ID находится в
          справочнике
      status:
        description: Статус заявки (новая, в работе, выполнена, отменена) генерируется
          после создания заявки
        type: string
      urgency:
        description: срочность
        type: string
    type: object
  dto.Source:
    description: Источник информации от кого был получен запрос. Поле name игнорируется
      при создании заявки.
    properties:
      id:
        description: уникальный идентификатор источника при Post запросе на создание
          заявки ОБЯЗАТЕЛЕН
        type: string
      name:
        description: Название источника игнорируется при создании заявки
        type: string
    type: object
  dto.SuccessfullyResp:
    description: Структура для ответа с где обычно ок и сообщние
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  dto.UserProfile:
    description: Структура для получения профиля пользователя. Все поля обязательны
      к заполнению
    properties:
      full_name:
        description: Полное имя или название организации
        type: string
      login:
        description: Логин для входа в систему, должен быть уникальным
        type: string
      role:
        description: Роль пользователя, например, "admin", "user", "otdel" и т.д.
        type: string
    type: object
host: localhost:8091
info:
  contact: {}
  description: API сервиса для отлова бродячих собак.
  title: Go Dog Trapping API
  version: "1.0"
paths:
  /auth/change-password:
    post:
      consumes:
      - application/json
      description: Смена пароля пользователя.
      parameters:
      - description: Change Password information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Change Password
      tags:
      - Auth
  /auth/refresh:
    get:
      description: Обновление токенов доступа и обновления. Если access токен истёк
        то делаешь get запрос без body с куками и получаешь новые токены в куках.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Refresh Token
      tags:
      - Auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя.
      parameters:
      - description: Account credentials
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.AuthCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sign In
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя.
      parameters:
      - description: Account information
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sign Up
      tags:
      - Auth
  /requests:
    get:
      description: Получение всех запросов на отлов бродячих собак. Доступно только
        для районных администраторов.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.RequestFull'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get All Requests
      tags:
      - Requests
    post:
      consumes:
      - application/json
      description: Отправка запроса на отлов бродячей собаки. Поля source_id и applicant_id
        заполнять ID из справочников. Поля name в этих полях игнорируются при отправке
        запроса. Доступно для всех авторизованных пользователей.
      parameters:
      - description: Request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RequestFull'
      produces:
      - application/json
      responses:
        "200":
          description: "ok\"\t\"Запрос успешно отправлен"
          schema:
            $ref: '#/definitions/dto.SuccessfullyResp'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Send Request
      tags:
      - Requests
  /requests/download_url:
    get:
      description: Получение URL для скачивания файла заявки в формате .docx. Требуется
        параметр number в query, номер заявки. Доступно для всех авторизованных пользователей.
      parameters:
      - description: Request Number
        in: query
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Download Request File URL
      tags:
      - Requests
  /requests_otdel:
    get:
      description: Получение запросов на отлов бродячих собак по отделу. Требуется
        параметр otdel_id в query, otdel_id находится в справочнике. Доступно только
        для районных администраторов.
      parameters:
      - description: Otdel ID
        in: query
        name: otdel_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.RequestFull'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get Requests By Otdel
      tags:
      - Requests
  /user/profile:
    get:
      description: Получение профиля пользователя.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserProfile'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get User Profile
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
